name: graphene_protector

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: Install poetry
              run:python -m pip install poetry
            - name: Install package
              run: poetry install --only main,test
            - name: Run tox
              # Run tox using the version of Python in `PATH`
              run: tox -e py
